### ISSUE TITLE
History - Create Object

### ISSUE THREAD

**Issue by chewwwwwwwwww** [cs2103aug2015-w11-1j/main#25]

**Comment by chewwwwwwwwww** [comment]
Stacks
redo
undo

Mutators
put task into stack()
getUndoTask()
getRedoTask()

**Comment by renfc145** [comment]
Created history object. Combined the 4 methods, UndoTask() getRedoTask() popUndo() pushRedo(), into 2: undo() and redo(). insert() inserts CommandDetails object into the undoStack.
